name       : libwww-perl
version    : 6.26
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.26.tar.gz : d0c5435275f8638ff36fff8f655ad2ccad1156e66cc47bfacfb9e44fc585b24f
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : WWW Perl Modules
description: |
    The libwww-perl collection is a set of Perl modules which provides a
    simple and consistent application programming interface to the
    World-Wide Web.  The main focus of the library is to provide classes
    and functions that allow you to write WWW clients. The library also
    contain modules that are of more general use and even classes that
    help you implement simple HTTP servers.
rundeps    :
    - perl-encode-locale
    - perl-file-listing
    - perl-html-parser
    - perl-http-cookies
    - perl-http-daemon
    - perl-http-negotiate
    - perl-lwp-protocol-https
    - perl-net-http
    - perl-try-tiny
    - perl-www-robotrules
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
