name       : libwww-perl
version    : 6.15
release    : 2
source     :
    - https://github.com/libwww-perl/libwww-perl/archive/6.15.tar.gz : 139ee902a72396553da0aefebdf02314974ae1781596c7cf008570337a9680d8
license    : Artistic-1.0-Perl
summary    : WWW Perl Modules
description: |
    The libwww-perl collection is a set of Perl modules which provides a
    simple and consistent application programming interface to the
    World-Wide Web.  The main focus of the library is to provide classes
    and functions that allow you to write WWW clients. The library also
    contain modules that are of more general use and even classes that
    help you implement simple HTTP servers.
patterns   :
    - /usr/share/man
setup      : |
    perl Makefile.PL --no-programs
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/lib/perl5/5.20.1
