name       : libwww-perl
version    : '6.47'
release    : 14
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.47.tar.gz : 3029d6efc2099c4175bf976d0db7fbab9771ada631010c809cb4664230898f53
homepage   : https://metacpan.org/pod/LWP
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : WWW Perl Modules
description: |
    The libwww-perl collection is a set of Perl modules which provides a simple and consistent application programming interface to the World-Wide Web.  The main focus of the library is to provide classes and functions that allow you to write WWW clients. The library also contain modules that are of more general use and even classes that help you implement simple HTTP servers.
builddeps  :
    - perl-data-dump
    - perl-encode-locale
    - perl-file-listing
    - perl-html-parser
    - perl-http-cookies
    - perl-http-daemon
    - perl-http-negotiate
    - perl-lwp-protocol-https
    - perl-ntlm
    - perl-scalar-list-utils
    - perl-test-fatal
    - perl-test-leaktrace
    - perl-test-needs
    - perl-test-requiresinternet
    - perl-www-robotrules
rundeps    :
    - perl-data-dump
    - perl-encode-locale
    - perl-file-listing
    - perl-html-parser
    - perl-http-cookies
    - perl-http-daemon
    - perl-http-negotiate
    - perl-libnet
    - perl-lwp-mediatypes
    - perl-lwp-protocol-https
    - perl-ntlm
    - perl-scalar-list-utils
    - perl-try-tiny
    - perl-www-robotrules
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
