name       : libwww-perl
version    : '6.32'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.32.tar.gz : 69016601111f45d80f7c40afb30c54e2af0059e7af3e5e50a24a0fc68e2f399a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : WWW Perl Modules
description: |
    The libwww-perl collection is a set of Perl modules which provides a
    simple and consistent application programming interface to the
    World-Wide Web.  The main focus of the library is to provide classes
    and functions that allow you to write WWW clients. The library also
    contain modules that are of more general use and even classes that
    help you implement simple HTTP servers.
builddeps  :
    - perl-encode-locale
    - perl-file-listing
    - perl-html-parser
    - perl-http-cookies
    - perl-http-daemon
    - perl-http-negotiate
    - perl-lwp-protocol-https
    - perl-net-http
    - perl-try-tiny
    - perl-www-robotrules
    - perl-test-fatal
    - perl-test-requiresinternet
rundeps    :
    - perl-encode-locale
    - perl-file-listing
    - perl-html-parser
    - perl-http-cookies
    - perl-http-daemon
    - perl-http-negotiate
    - perl-lwp-protocol-https
    - perl-net-http
    - perl-try-tiny
    - perl-www-robotrules
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
